version: "3"
services:
  node-1:
    build:
     context: .
     dockerfile: ./Docker/node1/Dockerfile
    ports: ["8081:8881"]
    volumes: [./app:/app]
    networks:
      node_net:
        ipv4_address: 172.16.238.101
    environment:
      FLASK_DEBUG: 1
      SECRET: WWPBLWPXjpTXyIBs
      FILES_PATH: "db/node1"
      NODE_IP: 172.16.238.101:8881
  node-2:
    build:
     context: .
     dockerfile: ./Docker/node2/Dockerfile
    ports: ["8082:8882"]
    volumes: [./app:/app]
    networks:
      node_net:
        ipv4_address: 172.16.238.102
    environment:
      FLASK_DEBUG: 1
      SECRET: OPpIMjDTTMYrsCcC
      FILES_PATH: "db/node2"
      NODE_IP: 172.16.238.102:8882
  node-3:
    build:
     context: .
     dockerfile: ./Docker/node3/Dockerfile
    ports: ["8083:8883"]
    volumes: [./app:/app]
    networks:
      node_net:
        ipv4_address: 172.16.238.103
    environment:
      FLASK_DEBUG: 1
      SECRET: qgOqQbewtODlmhdb
      FILES_PATH: "db/node3"
      NODE_IP: 172.16.238.103:8883
  node-4:
    build:
     context: .
     dockerfile: ./Docker/node4/Dockerfile
    ports: ["8084:8884"]
    volumes: [./app:/app]
    networks:
      node_net:
        ipv4_address: 172.16.238.104
    environment:
      FLASK_DEBUG: 1
      SECRET: APPYSNASUyfdIhky
      FILES_PATH: "db/node4"
      NODE_IP: 172.16.238.104:8884

networks:
  node_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
